### ISSUE TITLE
ProtocolLib Issue

### ISSUE THREAD

**Issue by Sub2Assassin** [DxsSucuk/TrollV4#12]
because the plugin requires protocollib to be installed...it has issues because that plugin is not updated for 1.20.1 I am using....it sends packets and players can't join.

Error Report

ERROR Couldn't place player in world
02.04 16:21:24 [Server] INFO net.minecraft.ReportedException: Sending packet
02.04 16:21:24 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2225) ~[?:?]
02.04 16:21:24 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2203) ~[?:?]
02.04 16:21:24 [Server] INFO at net.minecraft.server.players.PlayerList.sendPlayerPermissionLevel(PlayerList.java:1152) ~[paper-1.20.1.jar:git-Paper-196]
02.04 16:21:24 [Server] INFO at net.minecraft.server.players.PlayerList.sendPlayerPermissionLevel(PlayerList.java:1137) ~[paper-1.20.1.jar:git-Paper-196]
02.04 16:21:24 [Server] INFO at net.minecraft.server.players.PlayerList.sendPlayerPermissionLevel(PlayerList.java:996) ~[paper-1.20.1.jar:git-Paper-196]
02.04 16:21:24 [Server] INFO at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:297) ~[paper-1.20.1.jar:git-Paper-196]
02.04 16:21:24 [Server] INFO at net.minecraft.server.network.ServerLoginPacketListenerImpl.placeNewPlayer(ServerLoginPacketListenerImpl.java:202) ~[?:?]
02.04 16:21:24 [Server] INFO at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:183) ~[?:?]
02.04 16:21:24 [Server] INFO at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:85) ~[?:?]
02.04 16:21:24 [Server] INFO at net.minecraft.network.Connection.tick(Connection.java:602) ~[?:?]
02.04 16:21:24 [Server] INFO at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:234) ~[?:?]
02.04 16:21:24 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1586) ~[paper-1.20.1.jar:git-Paper-196]
02.04 16:21:24 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.1.jar:git-Paper-196]
02.04 16:21:24 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1393) ~[paper-1.20.1.jar:git-Paper-196]
02.04 16:21:24 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1170) ~[paper-1.20.1.jar:git-Paper-196]
02.04 16:21:24 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
02.04 16:21:24 [Server] INFO at java.lang.Thread.run(Thread.java:840) ~[?:?]
02.04 16:21:24 [Server] INFO Caused by: java.lang.NullPointerException: type cannot be null
02.04 16:21:24 [Server] INFO at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907) ~[guava-31.1-jre.jar:?]
02.04 16:21:24 [Server] INFO at com.comphenix.protocol.injector.StructureCache.getStructure(StructureCache.java:138) ~[ProtocolLib.jar:?]
02.04 16:21:24 [Server] INFO at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:126) ~[ProtocolLib.jar:?]
02.04 16:21:24 [Server] INFO at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:96) ~[ProtocolLib.jar:?]
02.04 16:21:24 [Server] INFO at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:553) ~[ProtocolLib.jar:?]
02.04 16:21:24 [Server] INFO at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:456) ~[ProtocolLib.jar:?]
02.04 16:21:24 [Server] INFO at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib.jar:?]
02.04 16:21:24 [Server] INFO at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib.jar:?]
02.04 16:21:24 [Server] INFO at net.minecraft.network.Connection.sendPacket(Connection.java:449) ~[?:?]
02.04 16:21:24 [Server] INFO at net.minecraft.network.Connection.send(Connection.java:392) ~[?:?]
02.04 16:21:24 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2217) ~[?:?]
02.04 16:21:24 [Server] INFO ... 16 more
02.04 16:21:24 [Disconnect] User Sub2Assassin has disconnected, reason: Invalid player data
02.04 16:23:07 [Server] INFO UUID of player Sub2Assassin is 0ec850bc-6c7c-38ef-818b-37609a0b4501
02.04 16:23:07 [Server] ERROR Couldn't place player in world
02.04 16:23:07 [Server] INFO net.minecraft.ReportedException: Sending packet
02.04 16:23:07 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2225) ~[?:?]
02.04 16:23:07 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2203) ~[?:?]
02.04 16:23:07 [Server] INFO at net.minecraft.server.players.PlayerList.sendPlayerPermissionLevel(PlayerList.java:1152) ~[paper-1.20.1.jar:git-Paper-196]
02.04 16:23:07 [Server] INFO at net.minecraft.server.players.PlayerList.sendPlayerPermissionLevel(PlayerList.java:1137) ~[paper-1.20.1.jar:git-Paper-196]
02.04 16:23:07 [Server] INFO at net.minecraft.server.players.PlayerList.sendPlayerPermissionLevel(PlayerList.java:996) ~[paper-1.20.1.jar:git-Paper-196]
02.04 16:23:07 [Server] INFO at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:297) ~[paper-1.20.1.jar:git-Paper-196]
02.04 16:23:07 [Server] INFO at net.minecraft.server.network.ServerLoginPacketListenerImpl.placeNewPlayer(ServerLoginPacketListenerImpl.java:202) ~[?:?]
02.04 16:23:07 [Server] INFO at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:183) ~[?:?]
02.04 16:23:07 [Server] INFO at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:85) ~[?:?]
02.04 16:23:07 [Server] INFO at net.minecraft.network.Connection.tick(Connection.java:602) ~[?:?]
02.04 16:23:07 [Server] INFO at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:234) ~[?:?]
02.04 16:23:07 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1586) ~[paper-1.20.1.jar:git-Paper-196]
02.04 16:23:07 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.1.jar:git-Paper-196]
02.04 16:23:07 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1393) ~[paper-1.20.1.jar:git-Paper-196]
02.04 16:23:07 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1170) ~[paper-1.20.1.jar:git-Paper-196]
02.04 16:23:07 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
02.04 16:23:07 [Server] INFO at java.lang.Thread.run(Thread.java:840) ~[?:?]
02.04 16:23:07 [Server] INFO Caused by: java.lang.NullPointerException: type cannot be null
02.04 16:23:07 [Server] INFO at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907) ~[guava-31.1-jre.jar:?]
02.04 16:23:07 [Server] INFO at com.comphenix.protocol.injector.StructureCache.getStructure(StructureCache.java:138) ~[ProtocolLib.jar:?]
02.04 16:23:07 [Server] INFO at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:126) ~[ProtocolLib.jar:?]
02.04 16:23:07 [Server] INFO at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:96) ~[ProtocolLib.jar:?]
02.04 16:23:07 [Server] INFO at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:553) ~[ProtocolLib.jar:?]
02.04 16:23:07 [Server] INFO at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:456) ~[ProtocolLib.jar:?]
02.04 16:23:07 [Server] INFO at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib.jar:?]
02.04 16:23:07 [Server] INFO at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib.jar:?]
02.04 16:23:07 [Server] INFO at net.minecraft.network.Connection.sendPacket(Connection.java:449) ~[?:?]
02.04 16:23:07 [Server] INFO at net.minecraft.network.Connection.send(Connection.java:392) ~[?:?]
02.04 16:23:07 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2217) ~[?:?]
02.04 16:23:07 [Server] INFO ... 16 more
02.04 16:23:07 [Disconnect] User Sub2Assassin has disconnected, reason: Invalid player data

**Comment by Sub2Assassin** [comment]
That dev is not active and maybe doesn't want to update the plugin...it would be better to remove that dependency and make it independent for future updates.

**Comment by DxsSucuk** [comment]
Protocol Lib is being used a lot inside the code to prevent the usage of NMS or custom Package builds. And since Paper will remove support for those starting with the next major update ProtocolLib will still be used. I will be looking into the package changes for the newer versions and check what exactly change to prevent this error on newer versions.
