### ISSUE TITLE
1.21?

### ISSUE THREAD

**Issue by proh14** [DxsSucuk/TrollV4#14]

**Comment by DxsSucuk** [comment]
Don't have anytime for it currently sadly.

**Comment by ghost** [comment]
```
22.07 14:35:12 [Server] ERROR Error occurred while enabling TrollV4 v4.5.19 (Is it up to date?)
22.07 14:35:12 [Server] INFO java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
22.07 14:35:12 [Server] INFO at TrollV4.jar/de.presti.trollv4.main.Main.onEnable(Main.java:57) ~[TrollV4.jar:?]
22.07 14:35:12 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
22.07 14:35:12 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-107-aa36ae6]
22.07 14:35:12 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-107-aa36ae6]
22.07 14:35:12 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
22.07 14:35:12 [Server] INFO at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.jar:1.21-107-aa36ae6]
22.07 14:35:12 [Server] INFO at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.jar:1.21-107-aa36ae6]
22.07 14:35:12 [Server] INFO at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753) ~[paper-1.21.jar:1.21-107-aa36ae6]
22.07 14:35:12 [Server] INFO at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515) ~[paper-1.21.jar:1.21-107-aa36ae6]
22.07 14:35:12 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.jar:1.21-107-aa36ae6]
22.07 14:35:12 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.jar:1.21-107-aa36ae6]
22.07 14:35:12 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-107-aa36ae6]
22.07 14:35:12 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
22.07 14:35:12 [Server] INFO [TrollV4] Disabling TrollV4 v4.5.19
```

**Comment by DxsSucuk** [comment]
Probably related to the Paper changes regarding their versioning.

**Comment by DxsSucuk** [comment]
Should be fixed in the lastest build.
