### ISSUE TITLE
cannot use command

### ISSUE THREAD

**Issue by 9995WX** [DxsSucuk/TrollV4#19]
Error for using command:
[21:12:50 ERROR]: Command exception: /troll
org.bukkit.command.CommandException: Unhandled exception executing command 'troll' in plugin TrollV4 v4.5.24
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[paper-1.21.1.jar:1.21.1-116-e7e1ab5]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.3.10.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.21.1.jar:1.21.1-116-e7e1ab5]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.21.1.jar:1.21.1-116-e7e1ab5]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.21.1.jar:1.21.1-116-e7e1ab5]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.21.1.jar:1.21.1-116-e7e1ab5]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.21.1.jar:1.21.1-116-e7e1ab5]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:443) ~[paper-1.21.1.jar:1.21.1-116-e7e1ab5]
        at net.minecraft.commands.Commands.performCommand(Commands.java:350) ~[paper-1.21.1.jar:1.21.1-116-e7e1ab5]
        at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[paper-1.21.1.jar:1.21.1-116-e7e1ab5]
        at net.minecraft.commands.Commands.performCommand(Commands.java:332) ~[paper-1.21.1.jar:1.21.1-116-e7e1ab5]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2218) ~[paper-1.21.1.jar:1.21.1-116-e7e1ab5]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2192) ~[paper-1.21.1.jar:1.21.1-116-e7e1ab5]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.1.jar:1.21.1-116-e7e1ab5]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.1.jar:1.21.1-116-e7e1ab5]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.1.jar:1.21.1-116-e7e1ab5]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1535) ~[paper-1.21.1.jar:1.21.1-116-e7e1ab5]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.1.jar:1.21.1-116-e7e1ab5]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.1.jar:1.21.1-116-e7e1ab5]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1512) ~[paper-1.21.1.jar:1.21.1-116-e7e1ab5]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1505) ~[paper-1.21.1.jar:1.21.1-116-e7e1ab5]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.1.jar:1.21.1-116-e7e1ab5]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1464) ~[paper-1.21.1.jar:1.21.1-116-e7e1ab5]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1471) ~[paper-1.21.1.jar:1.21.1-116-e7e1ab5]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1316) ~[paper-1.21.1.jar:1.21.1-116-e7e1ab5]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-116-e7e1ab5]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError
        at TrollV4.jar/de.presti.trollv4.shaded.com.cryptomorin.xseries.profiles.mojang.MojangAPI.<clinit>(MojangAPI.java:30) ~[TrollV4.jar:?]
        at TrollV4.jar/de.presti.trollv4.shaded.com.cryptomorin.xseries.profiles.objects.Profileable$UUIDProfileable.getProfile0(Profileable.java:265) ~[TrollV4.jar:?]
        at TrollV4.jar/de.presti.trollv4.shaded.com.cryptomorin.xseries.profiles.objects.cache.CacheableProfileable.getProfile(CacheableProfileable.java:41) ~[TrollV4.jar:?]
        at TrollV4.jar/de.presti.trollv4.shaded.com.cryptomorin.xseries.profiles.objects.Profileable.getDisposableProfile(Profileable.java:67) ~[TrollV4.jar:?]
        at TrollV4.jar/de.presti.trollv4.shaded.com.cryptomorin.xseries.profiles.builder.ProfileInstruction.apply(ProfileInstruction.java:162) ~[TrollV4.jar:?]
        at TrollV4.jar/de.presti.trollv4.utils.plugin.SkullUtil.getSkull(SkullUtil.java:17) ~[TrollV4.jar:?]
        at TrollV4.jar/de.presti.trollv4.invs.SetItems.buildSkull(SetItems.java:39) ~[TrollV4.jar:?]
        at TrollV4.jar/de.presti.trollv4.invs.InvManager.choicePlayer(InvManager.java:497) ~[TrollV4.jar:?]
        at TrollV4.jar/de.presti.trollv4.cmd.Haupt.onCommand(Haupt.java:115) ~[TrollV4.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        ... 27 more
Caused by: java.lang.NoSuchFieldException: None of the fields were found for FieldMemberHandle{protected/private GameProfile profile}
        at TrollV4.jar/de.presti.trollv4.shaded.com.cryptomorin.xseries.reflection.jvm.FieldMemberHandle.reflectJvm(FieldMemberHandle.java:189) ~[TrollV4.jar:?]
        at TrollV4.jar/de.presti.trollv4.shaded.com.cryptomorin.xseries.reflection.jvm.FieldMemberHandle.reflect(FieldMemberHandle.java:123) ~[TrollV4.jar:?]
        at TrollV4.jar/de.presti.trollv4.shaded.com.cryptomorin.xseries.profiles.ProfilesCore.<clinit>(ProfilesCore.java:66) ~[TrollV4.jar:?]
        at TrollV4.jar/de.presti.trollv4.shaded.com.cryptomorin.xseries.profiles.mojang.MojangAPI.<clinit>(MojangAPI.java:30) ~[TrollV4.jar:?]
        at TrollV4.jar/de.presti.trollv4.shaded.com.cryptomorin.xseries.profiles.objects.Profileable$UUIDProfileable.getProfile0(Profileable.java:265) ~[TrollV4.jar:?]
        at TrollV4.jar/de.presti.trollv4.shaded.com.cryptomorin.xseries.profiles.objects.cache.CacheableProfileable.getProfile(CacheableProfileable.java:41) ~[TrollV4.jar:?]
        at TrollV4.jar/de.presti.trollv4.shaded.com.cryptomorin.xseries.profiles.objects.Profileable.getDisposableProfile(Profileable.java:67) ~[TrollV4.jar:?]
        at TrollV4.jar/de.presti.trollv4.shaded.com.cryptomorin.xseries.profiles.builder.ProfileInstruction.apply(ProfileInstruction.java:162) ~[TrollV4.jar:?]
        at TrollV4.jar/de.presti.trollv4.utils.plugin.SkullUtil.getSkull(SkullUtil.java:17) ~[TrollV4.jar:?]
        at TrollV4.jar/de.presti.trollv4.invs.SetItems.buildSkull(SetItems.java:39) ~[TrollV4.jar:?]
        at TrollV4.jar/de.presti.trollv4.invs.InvManager.choicePlayer(InvManager.java:497) ~[TrollV4.jar:?]
        at TrollV4.jar/de.presti.trollv4.cmd.Haupt.onCommand(Haupt.java:115) ~[TrollV4.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        ... 27 more
        Suppressed: java.lang.NoSuchFieldException: Field named 'profile' was found but the types don't match: private net.minecraft.world.item.component.ResolvableProfile org.bukkit.craftbukkit.inventory.CraftMetaSkull.profile != FieldMemberHandle{protected/private GameProfile profile}
                at TrollV4.jar/de.presti.trollv4.shaded.com.cryptomorin.xseries.reflection.jvm.FieldMemberHandle.reflectJvm(FieldMemberHandle.java:182) ~[TrollV4.jar:?]

**Comment by DxsSucuk** [comment]
![image](https://github.com/user-attachments/assets/c77d0745-f129-4b81-a3c7-b11a84abfb43)

**Comment by DxsSucuk** [comment]
Should also be fixed now!
