### ISSUE TITLE
Can't see players on list in Paper 1.20.2

### ISSUE THREAD

**Issue by gabgat** [DxsSucuk/TrollV4#7]

**Comment by DxsSucuk** [comment]
Any logs?

**Comment by gabgat** [comment]
[12:16:00 INFO]: Draconix_Dust issued server command: /trollv4
[12:16:00 WARN]: java.lang.NullPointerException: Profile name must not be null
[12:16:00 WARN]:        at java.base/java.util.Objects.requireNonNull(Objects.java:235)
[12:16:00 WARN]:        at com.mojang.authlib.GameProfile.<init>(GameProfile.java:31)
[12:16:00 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftMetaSkull.setOwningPlayer(CraftMetaSkull.java:248)
[12:16:00 WARN]:        at TrollV4.jar//de.presti.trollv4.shaded.com.cryptomorin.xseries.SkullUtils.getSkull(SkullUtils.java:141)
[12:16:00 WARN]:        at TrollV4.jar//de.presti.trollv4.invs.SetItems.buildSkull(SetItems.java:33)
[12:16:00 WARN]:        at TrollV4.jar//de.presti.trollv4.invs.InvManager.choicePlayer(InvManager.java:495)
[12:16:00 WARN]:        at TrollV4.jar//de.presti.trollv4.cmd.Haupt.onCommand(Haupt.java:115)
[12:16:00 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[12:16:00 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[12:16:00 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:989)
[12:16:00 WARN]:        at org.bukkit.craftbukkit.v1_20_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[12:16:00 WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265)
[12:16:00 WARN]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:330)
[12:16:00 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:314)
[12:16:00 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2207)
[12:16:00 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$19(PlayerConnection.java:2167)
[12:16:00 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[12:16:00 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[12:16:00 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[12:16:00 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[12:16:00 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[12:16:00 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1324)
[12:16:00 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193)
[12:16:00 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[12:16:00 WARN]:        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1301)
[12:16:00 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1294)
[12:16:00 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[12:16:00 WARN]:        at net.minecraft.server.MinecraftServer.u_(MinecraftServer.java:1272)
[12:16:00 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1160)
[12:16:00 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[12:16:00 WARN]:        at java.base/java.lang.Thread.run(Thread.java:83

**Comment by DxsSucuk** [comment]
Looks like a bug in a library we use -> https://github.com/CryptoMorin/XSeries/releases/tag/v9.6.1.1

**Comment by DxsSucuk** [comment]
Try using this version https://github.com/DxsSucuk/TrollV4/suites/17361678683/artifacts/992086956

**Comment by gabgat** [comment]
Which one? Or both?

**Comment by gabgat** [comment]
Doesn't work unfortunately

**Comment by DxsSucuk** [comment]
Okay weird. Try the latest dev build. And use the TrollV4.jar not the -shaded.jar

**Comment by gabgat** [comment]
Where I can find it? Or I need to compile it?

**Comment by DxsSucuk** [comment]
Here https://github.com/DxsSucuk/TrollV4/actions/runs/6572622323
There should be a "TrollV4-all", if you download it you get a zip file, you only need the TrollV4.jar

**Comment by gabgat** [comment]
Ok, now it loads the players, but deactivating animation and then reloading the config causes the gui to close and do nothing

**Comment by DxsSucuk** [comment]
Very weird.
So It works if animations are on? But once you disable it, the GUI closes instantly or?

**Comment by DxsSucuk** [comment]
Could record the behaviour and send a Video and also send logs?

**Comment by gabgat** [comment]
Yeah, after reloading the config, doing /troll and select a player (I tried on myself) closes the gui

**Comment by gabgat** [comment]
It's spamming again:
Draconix_Dust issued server command: /troll
[10:46:57] [Server thread/WARN]: [TrollV4] Task #172007 for TrollV4 v4.5.16 generated an exception
java.lang.NullPointerException: Profile name must not be null
	at java.util.Objects.requireNonNull(Objects.java:235) ~[?:?]
	at com.mojang.authlib.GameProfile.<init>(GameProfile.java:31) ~[authlib-5.0.47.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.inventory.CraftMetaSkull.setOwningPlayer(CraftMetaSkull.java:248) ~[paper-1.20.2.jar:git-Paper-234]
	at de.presti.trollv4.shaded.com.cryptomorin.xseries.SkullUtils.getSkull(SkullUtils.java:162) ~[TrollV4.jar:?]
	at de.presti.trollv4.invs.SetItems.buildSkull(SetItems.java:38) ~[TrollV4.jar:?]
	at de.presti.trollv4.invs.InvManager.setPageOneTrolls(InvManager.java:383) ~[TrollV4.jar:?]
	at de.presti.trollv4.invs.InvManager$1.run(InvManager.java:175) ~[TrollV4.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.2.jar:git-Paper-234]
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.2.jar:git-Paper-234]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1470) ~[paper-1.20.2.jar:git-Paper-234]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.2.jar:git-Paper-234]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1379) ~[paper-1.20.2.jar:git-Paper-234]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.20.2.jar:git-Paper-234]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-234]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by DxsSucuk** [comment]
Fixed. I will be releasing the version on spigotmc now, with the fix.

**Comment by gabgat** [comment]
Thanks!

**Comment by DxsSucuk** [comment]
It has been released!
