### ISSUE TITLE
Potential unknown incompatibility with QualityArmory on 1.20.4 (but on 1.20.2 worked)

### ISSUE THREAD

**Issue by DartPower** [DxsSucuk/TrollV4#8]
Potential unknown incompatibility with QualityArmory on 1.20.4, but on 1.20.2 worked.

When i'm clicking on Player's head in /troll
```
[22:21:15 INFO]: DartPower issued server command: /troll
[22:21:17 ERROR]: Could not pass event InventoryClickEvent to QualityArmory v2.0.11
java.lang.NoSuchMethodError: 'java.lang.String com.mojang.authlib.properties.Property.getName()'
        at me.zombie_striker.qg.handlers.SkullHandler.getURL64(SkullHandler.java:88) ~[QualityArmory-v2.0.11.jar:?]
        at me.zombie_striker.customitemmanager.MaterialStorage.getMS(MaterialStorage.java:95) ~[QualityArmory-v2.0.11.jar:?]
        at me.zombie_striker.qg.api.QualityArmory.isAmmo(QualityArmory.java:379) ~[QualityArmory-v2.0.11.jar:?]
        at me.zombie_striker.qg.listener.QAListener.oninvClick(QAListener.java:413) ~[QualityArmory-v2.0.11.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1149.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2101]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2101]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2101]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3183) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.4.jar:git-Purpur-2101]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1483) ~[purpur-1.20.4.jar:git-Purpur-2101]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[purpur-1.20.4.jar:git-Purpur-2101]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1460) ~[purpur-1.20.4.jar:git-Purpur-2101]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1383) ~[purpur-1.20.4.jar:git-Purpur-2101]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1361) ~[purpur-1.20.4.jar:git-Purpur-2101]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1245) ~[purpur-1.20.4.jar:git-Purpur-2101]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:324) ~[purpur-1.20.4.jar:git-Purpur-2101]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:21:18 WARN]: java.lang.IllegalArgumentException: Material cannot be null
[22:21:18 WARN]:        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143)
[22:21:18 WARN]:        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:98)
[22:21:18 WARN]:        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:86)
[22:21:18 WARN]:        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:73)
[22:21:18 WARN]:        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:59)
[22:21:18 WARN]:        at TrollV4-v4.5.18.jar//de.presti.trollv4.invs.SetItems.buildItem(SetItems.java:61)
[22:21:18 WARN]:        at TrollV4-v4.5.18.jar//de.presti.trollv4.invs.InvManager.setPageOneTrolls(InvManager.java:372)
[22:21:18 WARN]:        at TrollV4-v4.5.18.jar//de.presti.trollv4.invs.InvManager.openPlayerInv(InvManager.java:347)
[22:21:18 WARN]:        at TrollV4-v4.5.18.jar//de.presti.trollv4.listener.GuiListener.onTrollGuiClick(GuiListener.java:200)
[22:21:18 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor996.execute(Unknown Source)
[22:21:18 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[22:21:18 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[22:21:18 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[22:21:18 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[22:21:18 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[22:21:18 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[22:21:18 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:3183)
[22:21:18 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:58)
[22:21:18 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:23)
[22:21:18 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:54)
[22:21:18 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[22:21:18 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[22:21:18 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[22:21:18 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1483)
[22:21:18 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194)
[22:21:18 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[22:21:18 WARN]:        at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1460)
[22:21:18 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1383)
[22:21:18 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[22:21:18 WARN]:        at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java:1361)
[22:21:18 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1245)
[22:21:18 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:324)
[22:21:18 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

This is a Troll plugin problem or Quality Armory bug?

**Comment by DxsSucuk** [comment]
Great Question, I will be looking into it. I am sadly unsure myself who is at fault here, but from the first look it seems like TrollV4.

**Comment by DxsSucuk** [comment]
Seems like QualityArmory doesn't support the latest version, since there are changes in the Property class. Which seems to set a null material? Which causes TrollV4 to not function. I would assume it's a bug on both sides, but for TrollV4 this just means that I was not careful enough with the null checks.

**Comment by DxsSucuk** [comment]
Yep this Issue is related to QualityArmory.
https://github.com/ZombieStriker/QualityArmory/issues/553
